
name: Build workflow
run-name: Build workflow
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: debian:bullseye
    steps:
    - name: Install Perl packages
      run: |
        apt-get update && apt-get install -y cpanminus make gcc openssl libssl-dev zlib1g-dev git
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v4
    - name: Install dzil
      run: cpanm --notest Dist::Zilla Dist::Zilla::App::Command::cover App::cpm Devel::Cover::Report::Coveralls https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.29.tar.gz https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.30.tar.gz
    - name: Install dzil author deps
      run: cpm install --show-build-log-on-failure -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil authordeps --missing)
    - name: Install distribution deps
      run: cpm install --show-build-log-on-failure -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil listdeps --author --missing)
    - name: Run smoke test
      run: dzil smoke --release --author
    - name: Run coverage test
      run: dzil cover -test -report coveralls
    - name: Run extended author test
      run: dzil xtest
